### ISSUE TITLE
Add 클래스 사용하지 않는 함수 add

### ISSUE THREAD

**Issue by myungah** [dahaech/StudentInfoSystem#9]
public void add(int id2, String name2, String department2, String phone2) {
        // TODO Auto-generated method stub

```
}
```

Add 클래스에서 이 함수를 사용하지 않습니다. 사용하지 않는다면 지워주시든가 아니면 함수를 넣은 용도를 밝혀주세요.

**Comment by bnewyork** [comment]
생성자 인데 디자인 구조와 맞지 않음으로 삭제하도록 하겠습니다.
